// User Reducer Types

export const SET_SIGNEDIN = "SET_SIGNEDIN";
export const SET_SIGNEDOUT = "SET_SIGNEDOUT";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_USER_DETAILS_CONTESTS = "UPDATE_USER_DETAILS_CONTESTS";
export const UPDATE_USER_DETAILS_COMMENTS = "UPDATE_USER_DETAILS_COMMENTS";

export const LOAD_REDUX_DATA_FIELDS = "LOAD_REDUX_DATA_FIELDS";

export const SET_USER_CANDIDATE = "SET_USER_CANDIDATE";
export const UNSET_USER_CANDIDATE = "UNSET_USER_CANDIDATE";
export const EDIT_USER_CANDIDATE = "EDIT_USER_CANDIDATE";
export const SET_USER_CANDIDATE_PICTURE = "SET_USER_CANDIDATE_PICTURE";

export const SET_USER_PICTURE = "SET_USER_PICTURE";
export const SET_USER_PICTURE_CONTESTS = "SET_USER_PICTURE_CONTESTS";
export const SET_USER_PICTURE_COMMENTS = "SET_USER_PICTURE_COMMENTS";

export const SET_USER_CONTEST = "SET_USER_CONTEST";
export const UNSET_USER_CONTEST = "UNSET_USER_CONTEST";
export const EDIT_USER_CONTEST = "EDIT_USER_CONTEST";
export const SET_USER_CONTEST_CANDIDATE = "SET_USER_CONTEST_CANDIDATE";
export const UNSET_USER_CONTEST_CANDIDATE = "UNSET_USER_CONTEST_CANDIDATE";

export const SET_CONTEST_COMMENT = "SET_CONTEST_COMMENT";

// UI Reducer Types

export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const STOP_LOADING_UI = "STOP_LOADING_UI";

// Data Reducer Types

export const SET_CANDIDATES = "SET_CANDIDATES";
export const SET_CANDIDATE = "SET_CANDIDATE";
export const UNSET_CANDIDATE = "UNSET_CANDIDATE";
export const EDIT_CANDIDATE = "EDIT_CANDIDATE";
export const SET_CANDIDATE_PICTURE = "SET_CANDIDATE_PICTURE";

export const SET_CONTEST = "SET_CONTEST";
export const SET_CONTESTS = "SET_CONTESTS";
export const UNSET_CONTEST = "UNSET_CONTEST";
export const EDIT_CONTEST = "EDIT_CONTEST";
export const SET_CONTEST_CANDIDATE = "SET_CONTEST_CANDIDATE";
export const UNSET_CONTEST_CANDIDATE = "UNSET_CONTEST_CANDIDATE";

export const SET_ALL_CLIENT_PLANS = "SET_ALL_CLIENT_PLANS";
export const SET_CLIENTS_LIST = "SET_CLIENTS_LIST";
export const SET_PLANS = "SET_PLANS";
export const LOADING_DATA = "LOADING_DATA";
export const STOP_LOADING_DATA = "STOP_LOADING_DATA";
export const SET_ACCOUNT_SUMMARY = "SET_ACCOUNT_SUMMARY";

export const SET_TRADE_ACCOUNT_LOG = "SET_TRADE_ACCOUNT_LOG";
export const SET_ACCOUNT_SUMMARY_LOG = "SET_ACCOUNT_SUMMARY_LOG";

// Votes

export const SET_CANDIDATE_VOTE = "SET_CANDIDATE_VOTE";
export const UNSET_CANDIDATE_VOTE = "UNSET_CANDIDATE_VOTE";
export const UPDATE_CANDIDATE_VOTE = "UPDATE_CANDIDATE_VOTE";

export const INCREMENT_CANDIDATE_VOTECOUNT = "INCREMENT_CANDIDATE_VOTECOUNT";
export const DECREMENT_CANDIDATE_VOTECOUNT = "DECREMENT_CANDIDATE_VOTECOUNT";
export const INCREMENT_CONTEST_VOTECOUNTTOTAL =
  "INCREMENT_CONTEST_VOTECOUNTTOTAL";
export const DECREMENT_CONTEST_VOTECOUNTTOTAL =
  "DECREMENT_CONTEST_VOTECOUNTTOTAL";
export const INCREMENT_CONTESTCANDIDATES_VOTECOUNT =
  "INCREMENT_CONTESTCANDIDATES_VOTECOUNT";
export const DECREMENT_CONTESTCANDIDATES_VOTECOUNT =
  "DECREMENT_CONTESTCANDIDATES_VOTECOUNT";
